server:
  port: 9000

eureka:
  instance:
      preferIpAddress: true
      hostname: base
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/


ribbon:
  eureka:
    enabled: true
