server:
  port: 9002

eureka:
  instance:
      preferIpAddress: true
      hostname: i3
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/


ribbon:
  eureka:
    enabled: true
