server:
  port: 9001

eureka:
  instance:
      preferIpAddress: true
      hostname: attachment
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/


ribbon:
  eureka:
    enabled: true
