server:
  port: 10000

sidecar:
  port: 8000

endpoints:
  restart:
    enabled: true
  shutdown:
    enabled: true
  health:
    sensitive: false

eureka:
  instance:
    hostname: gateway
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/


security:
  oauth2:
    authorization:
      checkTokenAccess: isAuthenticated()

spring:
  jpa:
    hibernate:
      ddl-auto: update
    database: mysql
    show-sql: true

  datasource:
    test-on-borrow: true
    validation-query: SELECT 1
    url: jdbc:mysql://127.0.0.1:3306/grei_uat?characterEncoding=UTF-8&autoReconnect=true&failOverReadOnly=false&zeroDateTimeBehavior=convertToNull&useSSL=true
    username: root
    password: liujx
    driver-class-name: com.mysql.jdbc.Driver

debug: true

